# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.13.6.4"
gem "cucumber", "5.2"
gem "capybara", "3.33"
gem "selenium-webdriver", "3.142.7"
gem "faker", "2.14"
gem "mongo", "2.13.1"
gem "rspec", "3.10"
gem "httparty", "0.20.0"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
